<a href="https://colab.research.google.com/github/JadeSCLim/fistRep/blob/master/python_stockmarket.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
pip install quandl

In [0]:
# The python programm for Share market
# Install the dependencies
import quandl
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [0]:
#Get the stock data
df = quandl.get("WIKI/FB")
# Take a look at the data
print(df.head())

In [0]:
# Get the Adjusted Close Price
df = df[['Adj. Close']]
#Take a look at the new data
print(df.head())

            Adj. Close
Date                  
2012-05-18     38.2318
2012-05-21     34.0300
2012-05-22     31.0000
2012-05-23     32.0000
2012-05-24     33.0300


In [0]:
# A variable for predicting 'n' days out into the future
forecast_out = 1
#Create another column (the target or dependent variable) shifted 'n' units up
df['Prediction'] = df[['Adj. Close']].shift(-forecast_out)
# print the new data set
#print(df.head())
# print the new data tail
print(df.tail())

In [0]:
### Create the independent data set (x) ###
# Convert the dataframe to a numpy array
X = np.array(df.drop(['Prediction'], 1))
# Remove the last 'n' rows
X = X[:-forecast_out]
print (X)

[[ 38.2318]
 [ 34.03  ]
 [ 31.    ]
 ...
 [164.89  ]
 [159.39  ]
 [160.06  ]]


In [0]:
### Create the dependent data set (y) ####
# Convert the dataframe to a numpy array (All of the values including the NaN's)
y = np.array(df['Prediction'])
# Get all of the y values except the last 'n' rows
y = y[:-forecast_out]
print (y)

[ 34.03  31.    32.   ... 159.39 160.06 152.19]


In [0]:
# Split the data into 80% training and 20% testing
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [0]:
# Create and train the Support Vector Machine (Regressor)
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
svr_rbf.fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
# Testing Model: Score returns the coefficient of determination R^2 of the prediction.
# The best possible score is 1.0
svm_confidence = svr_rbf.score(x_test, y_test)
print("svm confindence: ", svm_confidence)

svm confindence:  0.9936333655836255


In [0]:
# Create and train the Linear Regression Model
lr = LinearRegression()
# Train the model
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
# Testing Model: Score returns the coefficient of determination R^2 of the prediction.
# The best possible score is 1.0
lr_confidence = lr.score(x_test, y_test)
print("lr confindence: ", lr_confidence)

lr confindence:  0.9984936002820246


In [0]:
# Set x_forecast equal to the last 30 rows of the original data set from Adj. Close column
x_forecast = np.array(df.drop(['Prediction'],1))#[-forecast_out:]
print(x_forecast)

[[ 38.2318]
 [ 34.03  ]
 [ 31.    ]
 ...
 [159.39  ]
 [160.06  ]
 [152.19  ]]


In [0]:
# Print the prediction for the next 'n' days
lr_prediction = lr.predict(x_forecast)
print(lr_prediction)

[ 38.32627295  34.12503465  31.09543971 ... 159.46827621 160.13818664
 152.26923873]


In [0]:
# Print support vector regressor model predictions for the next 'n' days
svm_prediction = svr_rbf.predict(x_forecast)
print(svm_prediction)

[ 37.88670503  33.26379861  31.05831397 ... 159.85909029 159.84071805
 152.5358909 ]
